feat: add JSON transport
zwave-js/log-transports pull request #30
Opened 2021-08-27 09:45 UTC by marcus-j-davies

So,

This is my first real stab at Typescript.

there might be 1 or 2 things, I didn't get right (or check)

be gentle 😄

2021-08-28 14:30 UTC, AlCalzone requested changes

2021-08-28 14:30 UTC, AlCalzone commented on packages/json/src/index.ts
> +	}
I think you need to overwrite the `close` method of `Transport`. At least the built-in file transport does this:
https://github.com/winstonjs/winston/blob/2625f60c5c85b8c4926c65e98a591f8b42e0db9a/lib/winston/transports/file.js#L454

2021-08-28 14:30 UTC, AlCalzone commented on packages/json/src/index.ts
> +			level: options.level || "silly",
AFAIK this MUST be `"silly"` or changes to zwave-js's loglevel won't propagate properly.

2021-08-28 14:30 UTC, AlCalzone commented on packages/json/src/index.ts
> +	formattedMessageSymbol = Symbol.for("message");
No need for this to be a class member, just make it a const in the module scope

2021-09-01 12:13 UTC, AlCalzone commented
@raman325 What the point of having `formattedMessage` in addition to `message`?
formatted message is date + label + direction + primary tags + message + padding + secondary tags

If you want the formatted message, we could either add a property to the constructor to add the default format and overwrite the `message` with the symbol property one. Or we could leave it up to the transport consumer and overwrite `message` when the symbol property exists.

2021-09-01 12:16 UTC, AlCalzone commented
Also, if you use objectMode streams and skip the stringify, symbol properties will be included in the object:
![grafik](https://user-images.githubusercontent.com/17641229/131669605-e8e5d531-423e-414e-be63-3d36c6b4c2ac.png)
(this is with default formatting:)
```ts
j.format = createDefaultTransportFormat(false, false);
```

2021-09-01 12:37 UTC, AlCalzone approved these changes
I'll wait for feedback on the formatted message, but I'm okay with this now

2021-09-01 12:44 UTC, marcus-j-davies commented
currently using my own implementation, but will switch over to this one, once.
is this actually bundled with the driver?

2021-09-01 12:48 UTC, AlCalzone commented
No, each transport is a separate package you have to install yourself.

2021-09-01 15:21 UTC, raman325 commented
> @raman325 What the point of having `formattedMessage` in addition to `message`?
> formatted message is date + label + direction + primary tags + message + padding + secondary tags
> 
> If you want the formatted message, we could either add a property to the constructor to add the default format and overwrite the `message` with the symbol property one. Or we could leave it up to the transport consumer and overwrite `message` when the symbol property exists.

That's a fair point. To me `formattedMessage` > `message` because it allows the consumer to show the user the actual log message vs trying to recreate it from all the input parameters

2021-09-19 20:11 UTC, merged